# Generated by Django 2.1.7 on 2019-03-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.BigIntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='replies',
            name='comments_id',
            field=models.BigIntegerField(auto_created=True),
        ),
    ]
