# Generated by Django 2.1.7 on 2019-03-18 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20190317_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='replies',
            name='comments_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Comments'),
        ),
    ]
